services:
  web:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
      - FIREBASE_PROJECT_ID=whiskeywiz2
      - FIREBASE_API_KEY=AIzaSyCqZMaGpJGf5veYgTXmytg1bLerva-of0U
      - FIREBASE_AUTH_DOMAIN=whiskeywiz2.firebaseapp.com
      - FIREBASE_DATABASE_URL=https://whiskeywiz2-default-rtdb.firebaseio.com
      - FIREBASE_STORAGE_BUCKET=whiskeywiz2.appspot.com
      - FIREBASE_MESSAGING_SENDER_ID=555320797929
      - FIREBASE_APP_ID=1:555320797929:web:0d4b062d7f2ab330fc1e78
      - FIREBASE_MEASUREMENT_ID=G-SK0TJJEPF5
    command: npx nx serve whiskey-wiz --host 0.0.0.0

  firebase:
    image: andreysenov/firebase-tools
    volumes:
      - .:/app
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
      - FIREBASE_PROJECT_ID=whiskeywiz2
    working_dir: /app
    command: firebase emulators:start --project whiskeywiz2